// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PizzaShop.Infrastructure.Persistence;

#nullable disable

namespace PizzaShop.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PizzaShopDbContext))]
    [Migration("20260722110704_AddOrderItemPricingColumns")]
    partial class AddOrderItemPricingColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("order_number_seq");

            modelBuilder.Entity("MenuItemAllowedExtras", b =>
                {
                    b.Property<Guid>("MenuItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid");

                    b.HasKey("MenuItemId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("MenuItemAllowedExtras", (string)null);
                });

            modelBuilder.Entity("MenuItemBaseIngredients", b =>
                {
                    b.Property<Guid>("MenuItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid");

                    b.HasKey("MenuItemId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("MenuItemBaseIngredients", (string)null);
                });

            modelBuilder.Entity("PizzaShop.Application.Identity.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("UserAccounts", (string)null);
                });

            modelBuilder.Entity("PizzaShop.Domain.Catalog.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("ExtraPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients", (string)null);
                });

            modelBuilder.Entity("PizzaShop.Domain.Catalog.MenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("MenuItems", (string)null);
                });

            modelBuilder.Entity("PizzaShop.Domain.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId")
                        .IsUnique();

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("PizzaShop.Domain.Loyalty.LoyaltyAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<int>("PointsBalance")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("LoyaltyAccounts", (string)null);
                });

            modelBuilder.Entity("PizzaShop.Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AppliedPromotionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DeliveryFee")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTimeOffset?>("EstimatedReadyAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FulfillmentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("GuestTrackingToken")
                        .HasColumnType("uuid");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("PlacedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PointsRedeemed")
                        .HasColumnType("integer");

                    b.Property<int>("PointsToEarn")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderPaymentReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("RequestedFulfillmentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("GuestTrackingToken")
                        .IsUnique();

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("PizzaShop.Domain.Promotions.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MinOrderValue")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("UsageCount")
                        .HasColumnType("integer");

                    b.Property<int?>("UsageLimit")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Value")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Promotions", (string)null);
                });

            modelBuilder.Entity("PizzaShop.Domain.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("DeliveryFee")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<double>("DeliveryRadiusKm")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("FreeDeliveryThreshold")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<bool>("IsAcceptingOrders")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MinimumOrderValue")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OpeningHours")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Restaurants", (string)null);
                });

            modelBuilder.Entity("MenuItemAllowedExtras", b =>
                {
                    b.HasOne("PizzaShop.Domain.Catalog.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PizzaShop.Domain.Catalog.MenuItem", null)
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MenuItemBaseIngredients", b =>
                {
                    b.HasOne("PizzaShop.Domain.Catalog.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PizzaShop.Domain.Catalog.MenuItem", null)
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PizzaShop.Domain.Catalog.MenuItem", b =>
                {
                    b.OwnsMany("PizzaShop.Domain.Catalog.MenuItemVariant", "Variants", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsDefault")
                                .HasColumnType("boolean");

                            b1.Property<Guid>("MenuItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<decimal>("Price")
                                .HasPrecision(12, 2)
                                .HasColumnType("numeric(12,2)");

                            b1.HasKey("Id");

                            b1.HasIndex("MenuItemId");

                            b1.ToTable("MenuItemVariants", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MenuItemId");
                        });

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("PizzaShop.Domain.Customers.Customer", b =>
                {
                    b.OwnsMany("PizzaShop.Domain.Customers.CustomerAddress", "AddressBook", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsDefault")
                                .HasColumnType("boolean");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.HasKey("Id");

                            b1.HasIndex("CustomerId");

                            b1.ToTable("CustomerAddresses", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");

                            b1.OwnsOne("PizzaShop.Domain.ValueObjects.DeliveryAddress", "DeliveryAddress", b2 =>
                                {
                                    b2.Property<Guid>("CustomerAddressId")
                                        .HasColumnType("uuid");

                                    b2.Property<bool>("HasDeliveryAddress")
                                        .HasColumnType("boolean");

                                    b2.HasKey("CustomerAddressId");

                                    b2.ToTable("CustomerAddresses");

                                    b2.WithOwner()
                                        .HasForeignKey("CustomerAddressId");

                                    b2.OwnsOne("PizzaShop.Domain.ValueObjects.Address", "Address", b3 =>
                                        {
                                            b3.Property<Guid>("DeliveryAddressCustomerAddressId")
                                                .HasColumnType("uuid");

                                            b3.Property<string>("ApartmentNumber")
                                                .HasMaxLength(20)
                                                .HasColumnType("character varying(20)");

                                            b3.Property<string>("BuildingNumber")
                                                .IsRequired()
                                                .HasMaxLength(20)
                                                .HasColumnType("character varying(20)");

                                            b3.Property<string>("City")
                                                .IsRequired()
                                                .HasMaxLength(100)
                                                .HasColumnType("character varying(100)");

                                            b3.Property<string>("Notes")
                                                .HasMaxLength(500)
                                                .HasColumnType("character varying(500)");

                                            b3.Property<string>("PostalCode")
                                                .IsRequired()
                                                .HasMaxLength(10)
                                                .HasColumnType("character varying(10)");

                                            b3.Property<string>("Street")
                                                .IsRequired()
                                                .HasMaxLength(200)
                                                .HasColumnType("character varying(200)");

                                            b3.HasKey("DeliveryAddressCustomerAddressId");

                                            b3.ToTable("CustomerAddresses");

                                            b3.WithOwner()
                                                .HasForeignKey("DeliveryAddressCustomerAddressId");
                                        });

                                    b2.OwnsOne("PizzaShop.Domain.ValueObjects.GeoCoordinate", "Coordinate", b3 =>
                                        {
                                            b3.Property<Guid>("DeliveryAddressCustomerAddressId")
                                                .HasColumnType("uuid");

                                            b3.Property<double>("Latitude")
                                                .HasColumnType("double precision");

                                            b3.Property<double>("Longitude")
                                                .HasColumnType("double precision");

                                            b3.HasKey("DeliveryAddressCustomerAddressId");

                                            b3.ToTable("CustomerAddresses");

                                            b3.WithOwner()
                                                .HasForeignKey("DeliveryAddressCustomerAddressId");
                                        });

                                    b2.Navigation("Address")
                                        .IsRequired();

                                    b2.Navigation("Coordinate")
                                        .IsRequired();
                                });

                            b1.Navigation("DeliveryAddress")
                                .IsRequired();
                        });

                    b.Navigation("AddressBook");
                });

            modelBuilder.Entity("PizzaShop.Domain.Loyalty.LoyaltyAccount", b =>
                {
                    b.OwnsMany("PizzaShop.Domain.Loyalty.LoyaltyTransaction", "Transactions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("LoyaltyAccountId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("OccurredAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("Points")
                                .HasColumnType("integer");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.HasKey("Id");

                            b1.HasIndex("LoyaltyAccountId");

                            b1.ToTable("LoyaltyTransactions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("LoyaltyAccountId");
                        });

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("PizzaShop.Domain.Orders.Order", b =>
                {
                    b.OwnsOne("PizzaShop.Domain.ValueObjects.DeliveryAddress", "DeliveryAddress", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("HasDeliveryAddress")
                                .HasColumnType("boolean");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.OwnsOne("PizzaShop.Domain.ValueObjects.Address", "Address", b2 =>
                                {
                                    b2.Property<Guid>("DeliveryAddressOrderId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("ApartmentNumber")
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)");

                                    b2.Property<string>("BuildingNumber")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)");

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)");

                                    b2.Property<string>("Notes")
                                        .HasMaxLength(500)
                                        .HasColumnType("character varying(500)");

                                    b2.Property<string>("PostalCode")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("character varying(10)");

                                    b2.Property<string>("Street")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)");

                                    b2.HasKey("DeliveryAddressOrderId");

                                    b2.ToTable("Orders");

                                    b2.WithOwner()
                                        .HasForeignKey("DeliveryAddressOrderId");
                                });

                            b1.OwnsOne("PizzaShop.Domain.ValueObjects.GeoCoordinate", "Coordinate", b2 =>
                                {
                                    b2.Property<Guid>("DeliveryAddressOrderId")
                                        .HasColumnType("uuid");

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double precision");

                                    b2.HasKey("DeliveryAddressOrderId");

                                    b2.ToTable("Orders");

                                    b2.WithOwner()
                                        .HasForeignKey("DeliveryAddressOrderId");
                                });

                            b1.Navigation("Address")
                                .IsRequired();

                            b1.Navigation("Coordinate")
                                .IsRequired();
                        });

                    b.OwnsMany("PizzaShop.Domain.Orders.OrderItem", "Items", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("LineTotal")
                                .HasPrecision(12, 2)
                                .HasColumnType("numeric(12,2)");

                            b1.Property<Guid>("MenuItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("MenuItemName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Notes")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Quantity")
                                .HasColumnType("integer");

                            b1.Property<decimal>("UnitPrice")
                                .HasPrecision(12, 2)
                                .HasColumnType("numeric(12,2)");

                            b1.Property<Guid?>("VariantId")
                                .HasColumnType("uuid");

                            b1.Property<string>("VariantName")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.HasKey("Id");

                            b1.HasIndex("OrderId");

                            b1.ToTable("OrderItems", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.OwnsMany("PizzaShop.Domain.ValueObjects.OrderItemExtra", "Extras", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<Guid>("IngredientId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)");

                                    b2.Property<Guid>("OrderItemId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("Id");

                                    b2.HasIndex("OrderItemId");

                                    b2.ToTable("OrderItemExtras", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("OrderItemId");
                                });

                            b1.Navigation("Extras");
                        });

                    b.OwnsOne("PizzaShop.Domain.ValueObjects.ContactDetails", "Contact", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("Contact")
                        .IsRequired();

                    b.Navigation("DeliveryAddress");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("PizzaShop.Domain.Restaurant", b =>
                {
                    b.OwnsOne("PizzaShop.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("RestaurantId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ApartmentNumber")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("BuildingNumber")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Notes")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.HasKey("RestaurantId");

                            b1.ToTable("Restaurants");

                            b1.WithOwner()
                                .HasForeignKey("RestaurantId");
                        });

                    b.OwnsOne("PizzaShop.Domain.ValueObjects.GeoCoordinate", "Location", b1 =>
                        {
                            b1.Property<Guid>("RestaurantId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision");

                            b1.HasKey("RestaurantId");

                            b1.ToTable("Restaurants");

                            b1.WithOwner()
                                .HasForeignKey("RestaurantId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Location")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
